version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-3-220-98-137.compute-1.amazonaws.com
            database: dao6abmisd48mk
            schema: public
            user: ykkyqnfpxmteaj
            password: 08f636bda4627852c56587067258573d02e2b04eec5f935a4f902213c5b14066
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true