version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-3-224-38-18.compute-1.amazonaws.com
            database: d4u3vejts1gg9q
            schema: public
            user: egclvxsnihiwwg
            password: fae9c6372352f452c61add3df832cdde96e5664d728b7d3747e0f4adcc7d377e
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true